name: Build and Deploy to Branch

on:
  push:
    branches:
      - main # Déclenche l'action à chaque modification sur la branche principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permet d'écrire sur la branche de déploiement

    steps:
      - name: Checkout Code 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build

      - name: Deploy to Deploy Branch 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: deploy # Le nom de la branche qui sera créée/mise à jour automatiquement
          force_orphan: true # Garde la branche propre et légère
